# Generated by Django 6.0.4 on 2026-04-29 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='items',
        ),
        migrations.AddField(
            model_name='stockitem',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.purchase', verbose_name='Покупка'),
        ),
        migrations.AlterField(
            model_name='measurementunit',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='measurementunit',
            name='short_name',
            field=models.CharField(max_length=10, verbose_name='Коротка назва'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=255, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='product',
            name='measurement_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.measurementunit', verbose_name='Одиниця вимірювання'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.shop', verbose_name='Магазин'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Загальна ціна'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='description',
            field=models.TextField(verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='products',
            field=models.ManyToManyField(to='core.product', verbose_name='Продукти'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адреса'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Кількість'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Термін придатності'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='out_of_stock',
            field=models.BooleanField(default=False, verbose_name='Відсутність'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product', verbose_name='Продукт'),
        ),
    ]
