# Generated by Django 6.0.4 on 2026-04-30 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_purchase_items_stockitem_purchase_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='code',
        ),
        migrations.CreateModel(
            name='ProductCode',
            fields=[
                ('code', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='Код')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product', verbose_name='Продукт')),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва кроку')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('priority', models.PositiveIntegerField(default=0, verbose_name='Пріоритет')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.receipt', verbose_name='Рецепт')),
            ],
            options={
                'verbose_name': 'Крок рецепту',
                'verbose_name_plural': 'Кроки рецепту',
                'ordering': ['priority'],
            },
        ),
    ]
