# Generated by Django 6.0.4 on 2026-04-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_receipt_products_receiptproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='measurement_unit',
        ),
        migrations.AddField(
            model_name='receiptproduct',
            name='measurement_unit',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Одиниця вимірювання'),
        ),
        migrations.DeleteModel(
            name='MeasurementUnit',
        ),
    ]
