# Generated by Django 6.0.4 on 2026-04-30 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_product_measurement_unit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receiptproduct',
            options={'verbose_name': 'Продукт в рецепті', 'verbose_name_plural': 'Продукти в рецепті'},
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipies', models.ManyToManyField(to='core.receipt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Улюблений рецепт',
                'verbose_name_plural': 'Улюблені рецепти',
            },
        ),
    ]
